### ISSUE TITLE
Licence information

### ISSUE THREAD

**Issue by bdoin** [Aerlinger/maxwell#1]
Hi, we are considering using Maxwell in the educational software [GCompris](http://gcompris.net). We could not find a license information, could you please clarify it.

**Comment by Aerlinger** [comment]
Hey @bdoin so sorry for the very, very delayed response. Your message slipped under my radar somehow and I only just noticed it. I've added the MIT license to repository so feel free to use it as you wish.

Also, there have been several updates and bugfixes since your message. If you're interested, I'd be happy to hear more about what it is you're working on.

 - Anthony

**Comment by Aerlinger** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sample Github](https://trello.com/c/BiByCzpy/11-sample-github)
